version: "3.9"

services:
    db:
      image: mysql:latest
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: snippetbox
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin

volumes:
    db_data: {}
    wordpress_data: {}